### ISSUE TITLE
Feedback from beta version

### ISSUE THREAD

**Issue by brianmay** [dc297/mqttclpro#38]
Not so much complaints, just observations:

* Lost all settings on upgrade.
* When I first tried to enable a connection, it crashed. Sorry, don't have any more details.
* Looks like tasker setup needs to be redone. All references to app invalid.

**Comment by brianmay** [comment]
It looks like Tasker doesn't have any easy way of accessing the existing task or existing configuration that references a non-existent plugin. Don't particular want to have to reenter the JSON messages again...

**Comment by brianmay** [comment]
Since the update, it seems like multiple concurrent messages aren't handled anymore. Both get logged, but only one gets through to tasker. Tasker still has the correct setting to deal with clashes.

**Comment by dc297** [comment]
Hey Brian...thanx for taking out the time to provide feedback.

1. The first beta version did have a few bugs and might have caused the app to crash. I hope that it works fine after that. 
2. Yeah, I understand it will be a pain to migrate from the previous version of the app. Let me see if I can find a way to migrate data from previous version.
3. Yes, the tasker references will be rendered invalid.
4. Let me see if I can find a way to recover tasker configurations

Regarding concurrent messages, I am not facing the issue. I fire an MQTT message 4 times and my tasker action runs 4 times. Below is my task:

![screenshot_20171105-115957](https://user-images.githubusercontent.com/3163579/32413374-5fb90906-c236-11e7-9f7b-32722d7adc49.png)

Could you possibly share your configuration?

Cheers!
Deepesh

**Comment by brianmay** [comment]
I suspect the messages need to be sent *at the same time*. Even a one second delay means it works. I tried the following shell script to reproduce:

```
mosquitto_pub -h proxy.pri -t /action/Brian/ -m "$MSG"
sleep 1
mosquitto_pub -h proxy.pri -t /action/Brian/ -m "$MSG"
```

That works, remove the sleep and it doesn't work. The tasker event takes much longer then one second to process - I suspect in this case the problem might be that mqttclpro is still processing the message(???).

**Comment by mcspr** [comment]
Yep, can confirm that two messages arriving in quick succession do not trigger anything. Only *sometimes*:
```mosquitto_pub -h test.mosquitto.org -t test/topic/and/more -q 0 -m 123 & mosquitto_pub -h test.mosquitto.org -t test/topic/and/more -q 0 -m 123```

And running logcat on background service:
```
--------- beginning of main
11-07 21:11:14.929 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.CONNECTION_LOST
11-07 21:11:14.930 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Our broker id is 1 and our tasker pass thru id is -1
11-07 21:12:26.394 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:12:43.732 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:12:43.732 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID1626835310
11-07 21:12:43.867 20274 20274 I Query success: Seems like host doesnt support variable setting
11-07 21:12:50.710 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:12:50.710 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID870805023
11-07 21:12:50.737 20274 20274 I Query success: Seems like host doesnt support variable setting
11-07 21:12:53.871 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:12:53.871 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID580853208
11-07 21:12:53.904 20274 20274 I Query success: Seems like host doesnt support variable setting
11-07 21:12:53.932 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:12:53.933 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID580853208
11-07 21:14:23.972 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:14:23.972 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID923750080
11-07 21:14:24.049 20274 20274 I Query success: Seems like host doesnt support variable setting
11-07 21:14:24.077 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:14:24.077 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID2111030102
11-07 21:14:24.104 20274 20274 I Query success: Seems like host doesnt support variable setting
11-07 21:14:33.355 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:14:33.355 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID1261035616
11-07 21:14:33.388 20274 20274 I Query success: Seems like host doesnt support variable setting
11-07 21:14:33.411 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:14:33.411 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID1261035616
11-07 21:14:38.508 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:14:38.508 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID2094483112
11-07 21:14:38.534 20274 20274 I Query success: Seems like host doesnt support variable setting
11-07 21:14:38.697 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:14:38.697 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID1785520347
11-07 21:14:38.720 20274 20274 I Query success: Seems like host doesnt support variable setting
11-07 21:14:41.373 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:14:41.373 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID510638848
11-07 21:14:41.408 20274 20274 I Query success: Seems like host doesnt support variable setting
11-07 21:14:41.690 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:14:41.690 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID49327514
11-07 21:14:41.713 20274 20274 I Query success: Seems like host doesnt support variable setting
11-07 21:14:43.487 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:14:43.487 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID1236120223
11-07 21:14:43.513 20274 20274 I Query success: Seems like host doesnt support variable setting
11-07 21:14:43.533 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:14:43.533 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID1236120223
11-07 21:14:58.396 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:14:58.397 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID399325320
11-07 21:14:58.426 20274 20274 I Query success: Seems like host doesnt support variable setting
11-07 21:14:58.606 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:14:58.607 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID1766689506
11-07 21:14:58.630 20274 20274 I Query success: Seems like host doesnt support variable setting
11-07 21:15:02.263 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:15:02.263 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID1471422984
11-07 21:15:02.317 20274 20274 I Query success: Seems like host doesnt support variable setting
11-07 21:15:02.336 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:15:02.337 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID1177713193
11-07 21:15:02.362 20274 20274 I Query success: Seems like host doesnt support variable setting
11-07 21:15:05.991 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:15:05.992 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID1174231678
11-07 21:15:06.023 20274 20274 I Query success: Seems like host doesnt support variable setting
11-07 21:15:06.044 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with operation: in.dc297.mqttclpro.tasker.activity.intent.MESSAGE_ARRIVED
11-07 21:15:06.045 20274 20274 I in.dc297.mqttclpro.tasker.receivers.QueryReceiver: Received query with message ID1174231678
```

IDs are *sometimes* the same?

**Comment by dc297** [comment]
I have not been able to simulate the issue. However looking at the logcat @mcspr shared, I think I understand where the issue is. I am pushing an update which might fix the issue. Please test and let me know if it fixes the issue.

Cheers!

**Comment by brianmay** [comment]
Ok, thanks.

FYI this morning I noticed a weird issue where a message was received once (as per logs) but processed by tasker twice. Unfortunately, no I don't think I can reproduce this, however, I will keep an eye out in case it ever happens again.

**Comment by deepessh** [comment]
@brianmay I have a strong feeling that this issue should be fixed as well after the latest update. Let me know your observations.

**Comment by brianmay** [comment]
Unfortunately, it seems like I am still having the same problem. When I send two tasks at the same time, both get logged, however only the 2nd gets executed.

**Comment by deepessh** [comment]
Hey @brianmay 

This should be fixed now.

Cheers!

**Comment by brianmay** [comment]
Yes, looks fine now. Thanks!

**Comment by brianmay** [comment]
Oops, not sure if I should have closed this or not, as some parts are still outstanding.
