### ISSUE TITLE
Tasker not getting events

### ISSUE THREAD

**Issue by stipe76** [dc297/mqttclpro#45]
I have reinstalled your app multiple times, deleted events from Tasker, and recreated them, but Tasker does not pick up any changes. Your app shows the new messages, but Tasker does not see them.

**Comment by deepessh** [comment]
Please share what you are exactly trying to do.

**Comment by stipe76** [comment]
Uninstalled client
Deleted Tasker triggers
Reinstalled client
Added subscription topics
Added triggers in Tasker
Client correctly shows all messages
Tasker doesn't pick them up

I checked the log in Tasker, it randomly picks up a message change. Can you please check what the issue is, as this is currently not usable for me

**Comment by makervizic** [comment]
Hi dc297.
Thanks for the great job, i loved the previous version. Unfortunately I have the same issue with this update. Tasker isn't triggered anymore by MQTT CLient incoming messages. I've uninstalled everything, reinstalled, re-setup every events and tasks.
When I add an event on the MQTT Client message, it works. If I add a new one, then the new event works but other events stop working properly. 
It is also much slower than before, since I used to update 4 data/4 messages every second, now the only event that works is triggered every 5 or 10 messages from the broker.
Thanks for your help !!
Is there a way to get back the older version for a while ?

**Comment by deepessh** [comment]
Hi @makervizic 
I am able to simulate the issue you are having. Let me see if I can fix it quickly. Meanwhile you may download the previous version from https://github.com/dc297/mqttclpro/raw/v3.2.2/app/app-release.apk

@stipe76 Are you having this exact issue?

**Comment by stipe76** [comment]
Yes, seems to be the same issue

**Comment by makervizic** [comment]
Great, thanks !

**Comment by deepessh** [comment]
Hey guys. So I am planning to re-write the DB layer of the app. I had used requery along with reactivex at the DB layer which made writing data to the DB really slow. I think removing these libraries and writing the native code would make the whole process much faster.
But I am a little busy with some stuff right now. So it might be long before an update is available. Please bear with me.

**Comment by stipe76** [comment]
Reinstalled previous version and everything is working fine. Very tedious redoing the setup each time. It would be good if you could keep existing topics subscriptions that will continue to work in Tasker. Thanks for your efforts

**Comment by makervizic** [comment]
Thanks dc297, no problem to be patient, the previous version works fine to me so far.

**Comment by deepessh** [comment]
Hey just pushed a new update. The issues should be fixed.

Cheers!

**Comment by stipe76** [comment]
Installed latest version, same problems as before. Tasker still not reacting to changes. New topic changes show up randomly in the log, not every time they happen

Went through all steps to start from scratch, not working correctly. I won't upgrade again till other users can confirm correct functionality. Repeating all the steps each time is a headache

**Comment by deepessh** [comment]
@stipe76 which version did you upgrade to? Please do not install unless you see version 4.2.3

**Comment by stipe76** [comment]
I have 3 events happening at once. Tasker only gets the first one. Renders my notifications useless

**Comment by stipe76** [comment]
4.2.3, from Play Store

**Comment by deepessh** [comment]
can you share your event configuration? Also, if possible, the logcat.

**Comment by deepessh** [comment]
I hope you have set the correct collision handling for concurrent tasks in tasker.

**Comment by stipe76** [comment]
I have 3 events monitoring alarm status. One shows arm status, another shows date, and lastly time. If alarm is disarmed, 3 events happen, showing disarmed status, disarmed date, and disarmed time. These 3 events worked perfectly till recent updates. If I install apk you posted, all works fine.

Tasker now only picks up on date change. Alarm status and time are not seen. Client app works correctly and shows messages immediately

**Comment by deepessh** [comment]
So, three different messages are published on different topics? But only one is picked. Right?

**Comment by stipe76** [comment]
Did a bit more investigating. The first event triggers alphabetically. If I rename alarmdate to alarmtate for example, then alarmstatus triggers. Nothing else. So it seems only the first alphabetical event triggers, and stops there

**Comment by stipe76** [comment]
Yes, three different topics, three different events. Only first alphabetical fires off, then stops

**Comment by deepessh** [comment]
Strange, But it works for me. So I subscribed to 3 topics - hello, hello1, hello2. Setup separate events in tasker for them, add actions to display toasts with text 1, 2, 3 respectively. Publish messages on these three topics simultaneously using [HiveMQ's websoclets client](http://www.hivemq.com/demos/websocket-client/). And I am able to see all three toasts.

Please note I have three different tasks and three different events. I have only one broker added.

**Comment by stipe76** [comment]
Same here. Three topics, three messages published, three events, and three tasks. It used to work perfectly for months until recent updates. 

I have uninstalled the client, deleted events in Tasker, reinstalled the client, added topics, and recreated the events in Tasker, all multiple times. The only version that works correctly is the spk you posted

**Comment by stipe76** [comment]
*apk

**Comment by deepessh** [comment]
Are you using wildcards?

**Comment by deepessh** [comment]
@stipe76 I was able to simulate similar behavior while using wildcards. Pushed a fix for this. Do you have another device to test?

**Comment by stipe76** [comment]
No wildcards here, but that update seems to have fixed the issue. Working fine now, thanks!

**Comment by deepessh** [comment]
Great!
